<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Asset Count Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0px;
            color: #333;
        }
        header {
            text-align: center;
            margin-bottom: 20px;
        }
        h1 {
            margin-bottom: 5px;
        }
        .report-info {
            text-align: left;
            font-size: 12px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
            table-layout: fixed;
            /* word-break: break-word; */
        }
        th, td {
            padding: 6px 4px;
            border: 1px solid #aaa;
            text-align: left;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            max-width: 120px;
        }
        th {
            background-color: #f4f4f4;
        }
        tfoot td {
            font-weight: bold;
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
    </style>
</head>
<body>

<header>
    <h1>Asset Count Report</h1>
    <p><strong>Location: {{ $data_asset_count->location_show->location_data->name }}</strong></p>
</header>

<div class="report-info">
    <p>Date range: <span id="report-date">{{ \Carbon\Carbon::parse($data_asset_count->date_from)->format('F d, Y') . " - " . \Carbon\Carbon::parse($data_asset_count->date_to)->format('F d, Y') }}</span></p>
    <p>Count type: <span id="report-date">
        {{ $data_asset_count->type === 'quarter' ? 'Quarter' : ($data_asset_count->type === 'count' ? 'Count' : $data_asset_count->type) }}
    </span></p>
    <p>Quarter: <span id="report-date">
        @if($data_asset_count->quarter === 'Q1')
            1st Quarter
        @elseif($data_asset_count->quarter === 'Q2')
            2nd Quarter
        @elseif($data_asset_count->quarter === 'Q3')
            3rd Quarter
        @elseif($data_asset_count->quarter === 'Q4')
            4th Quarter
        @else
            {{ $data_asset_count->quarter }}
        @endif
    </span></p>
    <p>Lock Status: <span id="report-date">{{ $data_asset_count->is_finalized ? "Locked" : "Unlocked" }}</span></p>
    <p>Generated by: John Doe</p>
</div>

<table>
    <thead>
        <tr>
        <th>#</th>
        <th>Asset Tag</th>
        <th>Asset Name</th>
        <th>is Scanned</th>
        <th>Scanned By</th>
        <th>Scanned Date</th>
        <th>Company</th>
        <th>Department</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($data_asset_count->asset_count_plot as $count_plot)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $count_plot->asset->asset_id }}</td>
                <td>{{ $count_plot->asset->asset_description }}</td>
                <td>{{ $count_plot->isScanned ? 'Yes' : 'No' }}</td>
                <td>{{ $count_plot->scannedby ?? 'N/A' }}</td>
                <td>{{ $count_plot->scanned_at ? \Carbon\Carbon::parse($count_plot->scanned_date)->format('F d, Y h:i A') : 'N/A' }}</td>
                <td>{{ $count_plot->company->name }}</td>
                <td>{{ $count_plot->department->name }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7">Total Counted</td>
            <td>{{ count($data_asset_count->asset_count_plot) }}</td>
        </tr>
    </tfoot>
</table>

<div class="footer">
  <p>Asset Management System © 2025</p>
</div>

</body>
</html>
